Fix iteration when sorting is enabled
Define ‘sorted_items’ on a ‘_NoChildren’ class since that method is
used when iterating over nodes.  Without this defined, trying to
traverse a trie with sorting enabled results in an exception:

    AttributeError: '_NoChildren' object has no attribute 'sorted_items'

Fixes: https://github.com/google/pygtrie/pull/31
Reported-by: Pallab Pain <pallabkumarpain@gmail.com>